  GNU nano 4.8                                                                                                            elk-playbook.yml
---
  - name: ELK playbook
    hosts: elk
    become: true
    tasks:


    - name: Increase virtual memory
      command: sysctl -w vm.max_map_count=262144

    - ansible.posix.sysctl:
        name: vm.max_map_count
        value: 262144
        state: present
        reload: yes


    - name: Install docker.io
      apt:
        update_cache: yes
        name: docker.io
        state: present

    - name: Install python3-pip
      apt:
        name: python3-pip
        state: present

    - name: Install docker
      pip:
        name: docker
        state: present

    - name: Create first Container
      docker_container:
        name: elk
        image: sebp/elk:761
        state: started
        restart_policy: always
        published_ports:
          - 5601:5601
          - 9200:9200
          - 5044:5044

    - name: Enable Docker on boot
      systemd:
        name: docker
        enabled: yes



