  GNU nano 4.8                                                         metricbeat-playbook.yml
---
  - name: installing and launching metricbeat
    hosts: webservers
    become: yes
    tasks:

    - name: download metric deb
      command: curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.4.0-amd64.deb

    - name: install metric deb
      command: dpkg -i metricbeat-7.4.0-amd64.deb

    - name: drop in metric-config.yml
      copy:
        src: /etc/ansible/metric-config.yml
        dest: /etc/metricbeat/metricbeat.yml

    - name: enable and configure system module
      command: metricbeat modules enable docker

    - name: setup metricbeat
      command: metricbeat setup

    - name: start metricbeat service
      command: service metricbeat start

    - name: enable service metricbeat on boot
      systemd:
        name: metricbeat
        enabled: yes

